name: cw_core_flutter
description: Flutter-specific extensions for cw_core
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cw_core:
    path: ../cw_core
  path_provider: ^2.1.5
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
